# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Olivier Barais WebSite
email: barais@irisa.fr
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://olivier.barais.fr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: olivier.barais
github_username:  barais

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge

theme: minima
plugins:
  - jekyll-feed
  - jekyll-gallery-generator
  - jekyll-admin
  - jekyll_github_sample
  - jemoji
  - jekyll-gist
  - jekyll-youtube
  - jekyll-plantuml

jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration

excerpt_separator: <!--more-->
category_dir: /blog/categories
category_title_prefix: category:&nbsp;
permalink: /blog/posts/:categories/:year/:month/:day/:title.html
#permalink: /blog/posts/:year.:month.:day/:title.html
#permalink: /:categories/:title/

#destination: ./_site/
#plugins:     ./_plugins
#layouts:     ./_layouts
include:     ['.htaccess']
exclude:     ['run-jekyll.sh', 'Gemfile*', 'update_site.sh', 'update_site.sh','_assets/images']


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
gallery:
  # path to the gallery
  dir: photos
  # title for gallery index
  title: "Photos"

  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)

  # title prefix for gallery page. title=title_prefix+gallery_name
  title_prefix: "Photos: "
  # field to control sorting of galleries for the index page
  # (possible values are: title, date_time, best_image)
  sort_field: "title"
  # sizes for thumbnails
  #thumbnail_size:
  #  x: 400
  #  y: 400
  thumbnail_size:
    x: 350
    y: 350
  # custom configuration for individual gallery
  # best_image is image for the index page (defaults to last image)
  galleries:
    Bombannes2014:
        best_image: IMG_0851.JPG
    NoirmoutierPaques2014:
        best_image: WP_20140429_13_49_03_Pro__highres.jpg
    Maison:
        best_image: IMG_0913.JPG
feed:
    url: "http://olivier.barais.fr"
    author:
       twitter: "barais"
       picture: /img/me.gif
